export const SIGN_UP = 'SIGN UP';
export const LOG_IN = 'LOG IN';

export const MAKE_FRIEND_REQUEST = 'MAKE FRIEND REQUEST';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT FRIEND REQUEST';
export const WITHDRAW_FRIEND_REQUEST = 'WITHDRAW FRIEND REQUEST';
export const DECLINE_FRIEND_REQUEST = 'DECLINE FRIEND REQUEST';
export const REMOVE_FRIEND = 'REMOVE FRIEND';

export const GET_POSTS = 'GET POSTS';
export const CREATE_POST = 'CREATE POST';
export const UPDATE_POST = 'UPDATE POST';
export const DELETE_POST = 'DELETE POST';
export const LIKE_POST = 'LIKE POST';
export const UPDATE_POST_WITH_IMAGE = 'UPDATE_POST_WITH_IMAGE';

export const CREATE_COMMENT = 'CREATE COMMENT';
export const DELETE_COMMENT = 'DELETE COMMENT';
export const UPDATE_COMMENT = 'UPDATE COMMENT';
export const LIKE_COMMENT = 'LIKE COMMENT';

export const GET_USERS = 'GET USERS';
export const GET_USER_BY_ID = 'GET USER BY ID';
export const UPDATE_USER_WITH_IMAGE = 'UPDATE USER WITH IMAGE';
